name: "Bug report"
description: "For unintended behaviors"
title: "[Bug]: "
labels: bug
body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Fixing bugs can always be done by yourself through a pull request, We're more then to help you with some parts of implementing your own fix."
      options:
        - label: "I will implement a fix"
        
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        Please provide a clear and consice description of your bug. Remember a bug is **unintended** and a feature not being implemented is **not a bug**, and your issue may be closed for misleading labeling.
      placeholder: |
        ex: On startup I get this error
    validations:
      required: true
        
  - type: dropdown
    attributes:
      label: Version
      description: What version of the mod are you using?
      options:
        - Fabric 1.20.4

  - type: textarea
    attributes:
      label: Extra context
      description: |
        Any other information that may need to be needed about the problem can be put here.